export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export POWERLINE_COMMAND=~/PowerLine/scripts/powerline 
#export PATH=$PATH:~/ADT/sdk/platform-tools/
alias l='ls -GFh'
alias ls='ls -GFh'
alias ll='ls -l'
alias la='ls -la'
alias gen_scope='~/bin/gen_scope.sh'
